apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: crpocwes/dapperapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crpocwes/dapperapi 
    spec:
      containers:
        - name: crpocwes/dapperapi 
          image: crpocwes.azurecr.io/crpocwes/dapperapi 
          ports:
          - containerPort: 99999